package com.summerproject2026.DentalWave.service.impl;

// --- Spring Framework ---
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

// --- Lombok ---
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

// --- Java Standard Library ---
import java.util.List;
import java.util.stream.Collectors;

// --- Project: Service Interface ---
import com.summerproject2026.DentalWave.service.UserService;

// --- Project: DTOs ---
import com.summerproject2026.DentalWave.dto.UserDto;

// --- Project: Entities ---
import com.summerproject2026.DentalWave.entity.User;

// --- Project: Repositories ---
import com.summerproject2026.DentalWave.repository.UserRepository;
import com.summerproject2026.DentalWave.repository.RoleRepository;

// --- Project: Mapper ---
import com.summerproject2026.DentalWave.mapper.UserMapper;

// --- Project: Exceptions (create these simple exception classes if absent) ---
import com.summerproject2026.DentalWave.exception.DuplicateResourceException;
import com.summerproject2026.DentalWave.exception.ResourceNotFoundException;

/**
 * {@code UserServiceImpl} is the concrete implementation of {@link UserService}.
 *
 * Responsibilities:
 *   CRUD operations for User entities
 *   Business-rule validation (duplicate-email guard)
 *   Role-based and keyword-based user queries
 *   Enable / disable user accounts
 *   DTO <-> Entity translation via UserMapper
 *
 * Every public method that mutates state is annotated with
 * {@link Transactional} to guarantee atomicity and automatic rollback
 * on unchecked exceptions.
 *
 */
@Slf4j                   // Lombok: injects a SLF4J logger named `log`
@Service                 // Marks this class as a Spring-managed service bean
@RequiredArgsConstructor // Lombok: generates a constructor for all `final` fields (replaces @Autowired)
public class UserServiceImpl implements UserService {

    // ----------------------------------------------------------------
    //  Dependencies  (injected via constructor generated by Lombok)
    // ----------------------------------------------------------------

    /** Repository for User persistence operations. */
    private final UserRepository userRepository;

    /**
     * Repository for Role entity lookups.
     * Used when filtering users by role name.
     */
    private final RoleRepository roleRepository;

    /**
     * Mapper that converts between User entities and UserDto transfer objects.
     */
    private final UserMapper userMapper;


    // ================================================================
    //  PUBLIC API — CREATE
    // ================================================================

    /**
     * Creates a new user from the supplied DTO.
     *
     * <p>Steps:
     * <ol>
     *   <li>Validate that no existing user shares the same email (or username).</li>
     *   <li>Map the DTO to a {@link User} entity.</li>
     *   <li>Persist the entity.</li>
     *   <li>Map the saved entity back to a DTO and return it.</li>
     * </ol>
     *
     * @param userDto the data transfer object carrying the new user's data;
     *                must not be {@code null}
     * @return a {@link UserDto} reflecting the persisted state (includes generated ID)
     * @throws DuplicateResourceException if the email address is already registered
     */
    @Override
    @Transactional
    public UserDto createUser(UserDto userDto) {

        // Guard: reject duplicate emails / usernames before touching the DB
        checkDuplicateUser(userDto);

        // Convert incoming DTO → entity
        User user = userMapper.toEntity(userDto);

        // Persist — JPA assigns the generated primary key
        User savedUser = userRepository.save(user);

        log.debug("User persisted with id: {}", savedUser.getId());

        // Convert saved entity → DTO and hand back to the caller
        return userMapper.toDto(savedUser);
    }


    // ================================================================
    //  PUBLIC API — READ (single)
    // ================================================================

    /**
     * Retrieves a single user by their primary-key ID.
     *
     * @param id the database primary key of the user; must not be {@code null}
     * @return the corresponding {@link UserDto}
     * @throws ResourceNotFoundException if no user exists with the given {@code id}
     */
    @Override
    @Transactional(readOnly = true) // readOnly = true allows the JPA provider to skip dirty checking
    public UserDto getUserById(Long id) {
        // Delegate the "not found" error message to the private helper
        User user = getUserEntity(id);

        return userMapper.toDto(user);
    }

    /**
     * Retrieves a user by their email address.
     *
     * <p>Email addresses are treated as unique identifiers in this system.
     *
     * @param email the email address to search for; must not be {@code null}
     * @return the corresponding {@link UserDto}
     * @throws ResourceNotFoundException if no user is registered with {@code email}
     */
    @Override
    @Transactional(readOnly = true)
    public UserDto getUserByEmail(String email) {

        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "User not found with email: " + email));

        return userMapper.toDto(user);
    }


    // ================================================================
    //  PUBLIC API — READ (collections)
    // ================================================================

    /**
     * Returns every user in the system, mapped to DTOs.
     *
     * <p>Note: for large datasets consider adding pagination
     * ({@code Pageable}) to avoid loading the entire table into memory.
     *
     * @return an unmodifiable list of all {@link UserDto}s; never {@code null}
     */
    @Override
    @Transactional(readOnly = true)
    public List<UserDto> getAllUsers() {
        // Fetch all users from the database
        return userRepository.findAll()
                // A Stream is a pipeline that lets you process each element one at a time
                .stream()
                // Convert each User entity to a UserDto using the  user mapper
                .map(UserMapper::toDto)
                // Collect the results into a list
                .collect(Collectors.toList());
    }

    /**
     * Returns all users that possess a specific role.
     *
     * <p>The {@code role} parameter is compared case-insensitively against
     * stored role names (e.g. "ADMIN", "admin", "Admin" are equivalent).
     *
     * @param role the role name to filter by; must not be {@code null}
     * @return a list of matching {@link UserDto}s; empty list if none found
     */
    @Override
    @Transactional(readOnly = true)
    public List<UserDto> getUsersByRole(String role) {

        //   List<User> findByRoles_NameIgnoreCase(String roleName);
        return userRepository.findByRoles_NameIgnoreCase(role)
                .stream()
                .map(UserMapper::toDto)
                .collect(Collectors.toList());
    }

    /**
     * Full-text / keyword search across user fields.
     *
     * <p>The exact fields searched (e.g. first name, last name, email,
     * username) are determined by the underlying repository query.
     * A typical JPQL query would use {@code LIKE %:keyword%} across
     * those columns.
     *
     * @param keyword the search term; must not be {@code null}
     * @return a list of matching {@link UserDto}s; empty list if none match
     */
    @Override
    @Transactional(readOnly = true)
    public List<UserDto> searchUsers(String keyword) {

        // Assumes UserRepository exposes:
        //   List<User> searchByKeyword(String keyword);
        // with a @Query that checks multiple columns.
        return userRepository.searchByKeyword(keyword)
                .stream()
                .map(UserMapper::toDto)
                .collect(Collectors.toList());
    }


    // ================================================================
    //  PUBLIC API — UPDATE
    // ================================================================

    /**
     * Fully updates an existing user identified by {@code id}.
     *
     * <p>Only fields present in the supplied {@link UserDto} are applied;
     * the mapper should be configured to ignore {@code null} values if
     * partial updates are desired (see MapStruct {@code @BeanMapping}).
     *
     * @param id      the primary key of the user to update
     * @param userDto the new field values; must not be {@code null}
     * @return the updated {@link UserDto}
     * @throws ResourceNotFoundException  if no user exists with {@code id}
     * @throws DuplicateResourceException if the new email conflicts with another user
     */
    @Override
    @Transactional
    public UserDto updateUser(Long id, UserDto userDto) {

        // 1. Verify the target user exists
        User existingUser = getUserEntity(id);

        // 2. If the email is changing, verify it is not already taken by someone else
        if (!existingUser.getEmail().equalsIgnoreCase(userDto.getEmail())) {
            checkDuplicateUser(userDto);
        }

        // 3. Apply the DTO values onto the existing managed entity.
        //    Using the mapper keeps field-mapping logic in one place.
        //    The mapper call below mutates `existingUser` in place.
        userMapper.updateEntityFromDto(userDto, existingUser);

        // 4. Persist — because `existingUser` is a JPA managed entity
        //    inside a @Transactional method, `save()` is technically
        //    optional (dirty-checking will flush changes). Calling it
        //    explicitly makes the intent clear.
        User updatedUser = userRepository.save(existingUser);

        return userMapper.toDto(updatedUser);
    }


    // ================================================================
    //  PUBLIC API — DELETE
    // ================================================================

    /**
     * Permanently removes the user identified by {@code id}.
     *
     * <p>Downstream relationships (e.g. foreign-key constraints) should be
     * handled at the database level (CASCADE) or in the entity mappings
     * ({@code orphanRemoval = true}).
     *
     * @param id the primary key of the user to delete
     * @throws ResourceNotFoundException if no user exists with {@code id}
     */
    @Override
    @Transactional
    public void deleteUser(Long id) {

        // Verify existence before attempting deletion to provide a
        // meaningful error rather than a silent no-op.
        User user = getUserEntity(id);

        userRepository.delete(user);
    }


    // ================================================================
    //  PUBLIC API — ACCOUNT STATUS
    // ================================================================

    /**
     * Activates the user account identified by {@code id}.
     *
     * <p>Sets the {@code enabled} flag to {@code true} on the entity,
     * which Spring Security respects during authentication.
     *
     * @param id the primary key of the user to enable
     * @return the updated {@link UserDto} with {@code enabled = true}
     * @throws ResourceNotFoundException if no user exists with {@code id}
     */
    @Override
    @Transactional
    public UserDto enableUser(Long id) {
        // Get the user by id
        User user = getUserEntity(id);
        // activate the user, enable
        user.setEnabled(true);
        // Save the activated user
        User savedUser = userRepository.save(user);

        return userMapper.toDto(savedUser);
    }

    /**
     * Deactivates the user account identified by {@code id}.
     *
     * <p>Sets the {@code enabled} flag to {@code false}, preventing
     * the user from authenticating without deleting their data.
     *
     * @param id the primary key of the user to disable
     * @return the updated {@link UserDto} with {@code enabled = false}
     * @throws ResourceNotFoundException if no user exists with {@code id}
     */
    @Override
    @Transactional
    public UserDto disableUser(Long id) {
        // Get the user to de-activate
        User user = getUserEntity(id);
        // De-activate user
        user.setEnabled(false);
        // Save de-activated user
        User savedUser = userRepository.save(user);

        return userMapper.toDto(savedUser);
    }


    /**
     * Retrieves a user by their username.
     *
     * @param username the username to search for; must not be {@code null}
     * @return the corresponding {@link UserDto}
     * @throws ResourceNotFoundException if no user is registered with {@code username}
     */
    @Override
    @Transactional(readOnly = true)
    public UserDto getUserByUsername(String username) {
        // Find user by username or throw ResourceNotFoundException
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "User not found with username: " + username));

        return userMapper.toDto(user);
    }
    // ================================================================
    //  PRIVATE HELPERS
    // ================================================================

    /**
     * Validates that the email address in {@code userDto} is not already
     * registered to another user in the database.
     *
     * <p>Called before both {@link #createUser} and the email-change path
     * of {@link #updateUser} to keep the duplicate-check logic in one place.
     *
     * @param userDto the DTO whose email to validate
     * @throws DuplicateResourceException if the email is already in use
     */
    private void checkDuplicateUser(UserDto userDto) {
        // Check by email — the most common uniqueness constraint
        boolean emailExists = userRepository.existsByEmail(userDto.getEmail());

        if (emailExists) {
            log.warn("Duplicate email detected: {}", userDto.getEmail());
            throw new DuplicateResourceException(
                    "A user with email '" + userDto.getEmail() + "' already exists.");
        }

        // Also check username uniqueness
        boolean usernameExists = userRepository.existsByUsername(userDto.getUsername());

        if (usernameExists) {
            log.warn("Duplicate username detected: {}", userDto.getUsername());
            throw new DuplicateResourceException(
                    "Username '" + userDto.getUsername() + "' is already taken.");
        }
    }

    /**
     * Fetches a {@link User} entity by primary key, throwing a descriptive
     * {@link ResourceNotFoundException} if it does not exist.
     *
     * <p>This private helper centralises the "find or throw" pattern so that
     * every public method that needs an entity can delegate to it rather than
     * repeating the {@code orElseThrow} boilerplate.
     *
     * @param id the primary key to look up
     * @return the found {@link User} entity; never {@code null}
     * @throws ResourceNotFoundException if no record exists for {@code id}
     */
    private User getUserEntity(Long id) {
        return userRepository.findById(id)
                .orElseThrow(() -> {
                    log.warn("User not found with id: {}", id);
                    return new ResourceNotFoundException("User not found with id: " + id);
                });
    }
}