spring.application.name=DentalWave
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/dentalwave
spring.datasource.username=demarisghide
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# SHA256 encryption
app.jwt-secret=9dbc1fb155571cab62b1633235dc76e2e75753623182c35d5b3aa4656266bec9
# Expiration time in milliseconds - 7 days
app.jwt-expiration-milliseconds=604800000
# Plain text password for default admin user
app.admin-user-password=Password123
app.manager-user-username=
app.manager-user-password=
app.hr-user-username=
app.hr-user-password=
app.assistant-user-username=
app.assistant-user-password=