spring.application.name=AssistantScheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/assistantscheduler
spring.datasource.username=YOUR_DATABASE_USERNAME
spring.datasource.password=YOUR_DATABASE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt-secret=YOUR_BASE64_256_BIT_JWT_SECRET
app.jwt-expiration-milliseconds=604800000

app.admin-user-username=admin
app.admin-user-password=YOUR_ADMIN_PASSWORD
app.manager-user-username=manager
app.manager-user-password=YOUR_MANAGER_PASSWORD
app.hr-user-username=hr
app.hr-user-password=YOUR_HR_PASSWORD
app.assistant-user-username=assistant
app.assistant-user-password=YOUR_ASSISTANT_PASSWORD

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
