# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/assistantscheduler
spring.datasource.username=abigailclose
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
spring.application.name=AssistantScheduler

# JWT
app.jwt-secret=0d/BMArwXwVJjzgBlydeudR4OHld+o392pU2pVBCJOAxrNiefwemIC1fwQ60EJToWXKriKjFiWM1qpxYb7xQiw==
app.jwt-expiration-milliseconds=604800000

# Default test users
app.admin-user-username=admin
app.admin-user-password=password111

app.manager-user-username=manager
app.manager-user-password=password111

app.hr-user-username=hr
app.hr-user-password=password111

app.assistant-user-username=assistant
app.assistant-user-password=password111
